name: "Setup"
description: "Enable corepack, setup Node.js with yarn cache, and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "20"
        cache: "yarn"

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
