//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type TaskFindManyArgs = $FindManyArgs<$Schema, "Task">;
export type TaskFindUniqueArgs = $FindUniqueArgs<$Schema, "Task">;
export type TaskFindFirstArgs = $FindFirstArgs<$Schema, "Task">;
export type TaskExistsArgs = $ExistsArgs<$Schema, "Task">;
export type TaskCreateArgs = $CreateArgs<$Schema, "Task">;
export type TaskCreateManyArgs = $CreateManyArgs<$Schema, "Task">;
export type TaskCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Task">;
export type TaskUpdateArgs = $UpdateArgs<$Schema, "Task">;
export type TaskUpdateManyArgs = $UpdateManyArgs<$Schema, "Task">;
export type TaskUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Task">;
export type TaskUpsertArgs = $UpsertArgs<$Schema, "Task">;
export type TaskDeleteArgs = $DeleteArgs<$Schema, "Task">;
export type TaskDeleteManyArgs = $DeleteManyArgs<$Schema, "Task">;
export type TaskCountArgs = $CountArgs<$Schema, "Task">;
export type TaskAggregateArgs = $AggregateArgs<$Schema, "Task">;
export type TaskGroupByArgs = $GroupByArgs<$Schema, "Task">;
export type TaskWhereInput = $WhereInput<$Schema, "Task">;
export type TaskSelect = $SelectInput<$Schema, "Task">;
export type TaskInclude = $IncludeInput<$Schema, "Task">;
export type TaskOmit = $OmitInput<$Schema, "Task">;
export type TaskGetPayload<Args extends $SelectIncludeOmit<$Schema, "Task", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Task", Args, Options>;
