name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Stratal better? We'd love to hear it.

        > Have a question? Please use [GitHub Discussions](https://github.com/strataljs/stratal/discussions) instead.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this feature solve? Why is it needed?
      placeholder: I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? Include API examples or pseudocode if helpful.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about or workarounds you're currently using.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references that might help.
    validations:
      required: false

  - type: checkboxes
    id: pr
    attributes:
      label: Willingness to Contribute
      options:
        - label: I'm willing to submit a pull request for this feature.
