import { ZModelCodeGenerator } from '@zenstackhq/language'
import type { Model } from '@zenstackhq/language/ast'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { ConnectionInfo } from '../utils.js'
import {
  getDatasource,
  getDatasourceProvider,
  getEnumsForModels,
  stripConnectionAttribute,
  toUpperSnakeCase,
} from '../utils.js'

export function generateConnectionSchemas(
  outputDir: string,
  model: Model,
  connections: Map<string, ConnectionInfo>,
): void {
  const datasource = getDatasource(model)
  const mainProvider = datasource ? getDatasourceProvider(datasource) : 'postgresql'
  const codeGenerator = new ZModelCodeGenerator()

  for (const [connName, connInfo] of connections) {
    const provider = connInfo.provider ?? mainProvider ?? 'postgresql'
    const envVar = `${toUpperSnakeCase(connName)}_DATABASE_URL`

    const lines: string[] = [
      `// Auto-generated by @stratal/zenstack-plugin \u2014 DO NOT EDIT`,
      '',
      'datasource db {',
      `  provider = "${provider}"`,
      `  url = env("${envVar}")`,
      '}',
      '',
    ]

    const enums = getEnumsForModels(model, connInfo.modelNames)
    for (const enumDecl of enums) {
      lines.push(codeGenerator.generate(enumDecl))
      lines.push('')
    }

    for (const dataModel of connInfo.models) {
      const modelText = codeGenerator.generate(dataModel)
      lines.push(stripConnectionAttribute(modelText))
      lines.push('')
    }

    const filePath = join(outputDir, 'connections', connName, 'schema.zmodel')
    mkdirSync(dirname(filePath), { recursive: true })
    writeFileSync(filePath, lines.join('\n'), 'utf-8')
  }
}
