import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { ConnectionInfo } from '../utils'

export function generateSlicingFile(
  outputDir: string,
  connections: Map<string, ConnectionInfo>,
): void {
  const lines: string[] = [
    '// Auto-generated by @stratal/zenstack-plugin \u2014 DO NOT EDIT',
    'export const connectionSlicing = {',
  ]

  for (const [connName, connInfo] of connections) {
    const modelNames = connInfo.modelNames
      .map(n => `'${n}'`)
      .join(', ')
    lines.push(`  ${connName}: { includedModels: [${modelNames}] as const },`)
  }

  lines.push('} as const')
  lines.push('')

  const connectionNames = [...connections.keys()].map(n => `'${n}'`).join(', ')
  lines.push(`export const connectionNames = [${connectionNames}] as const`)
  lines.push('export type ConnectionNames = typeof connectionNames[number]')
  lines.push('')

  const filePath = join(outputDir, 'slicing.ts')
  mkdirSync(dirname(filePath), { recursive: true })
  writeFileSync(filePath, lines.join('\n'), 'utf-8')
}
