import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { ConnectionInfo } from '../utils.js'

export function generateSlicingFile(
  outputDir: string,
  connections: Map<string, ConnectionInfo>,
  defaultConnection: string,
): void {
  const lines: string[] = [
    '// Auto-generated by @stratal/zenstack-plugin \u2014 DO NOT EDIT',
    "import type { SchemaType } from './schema'",
    '',
    'export const connectionSlicing = {',
  ]

  for (const [connName, connInfo] of connections) {
    const modelNames = connInfo.modelNames
      .map(n => `'${n}'`)
      .join(', ')
    lines.push(`  ${connName}: { includedModels: [${modelNames}] as const },`)
  }

  lines.push('} as const')
  lines.push('')

  const connectionNames = [...connections.keys()].map(n => `'${n}'`).join(', ')
  lines.push(`export const connectionNames = [${connectionNames}] as const`)
  lines.push('export type ConnectionNames = typeof connectionNames[number]')
  lines.push('')

  lines.push('type _ConnectionSlicing = typeof connectionSlicing')
  lines.push('')

  lines.push("declare module '@stratal/framework/database' {")
  lines.push('  interface DatabaseSchema { type: SchemaType }')
  lines.push('  interface DatabaseSlicingRegistry extends _ConnectionSlicing {}')
  lines.push(`  interface DefaultDatabaseConnection { name: '${defaultConnection}' }`)
  lines.push('}')
  lines.push('')

  const filePath = join(outputDir, 'slicing.ts')
  mkdirSync(dirname(filePath), { recursive: true })
  writeFileSync(filePath, lines.join('\n'), 'utf-8')
}
