import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { ConnectionInfo } from '../utils'

export function generateTypesFile(
  outputDir: string,
  connections: Map<string, ConnectionInfo>,
  defaultConnection: string,
): void {
  const lines: string[] = [
    '// Auto-generated by @stratal/zenstack-plugin \u2014 DO NOT EDIT',
    "import type { SchemaType } from './schema'",
    '',
    "declare module '@stratal/framework/database' {",
    '  interface DatabaseSchema { type: SchemaType }',
    '  interface DatabaseSlicingRegistry {',
  ]

  for (const [connName, connInfo] of connections) {
    const modelNames = connInfo.modelNames
      .map(n => `'${n}'`)
      .join(', ')
    lines.push(`    ${connName}: { includedModels: readonly [${modelNames}] }`)
  }

  lines.push('  }')
  lines.push(`  interface DefaultDatabaseConnection { name: '${defaultConnection}' }`)
  lines.push('}')
  lines.push('')

  const filePath = join(outputDir, 'database.types.ts')
  mkdirSync(dirname(filePath), { recursive: true })
  writeFileSync(filePath, lines.join('\n'), 'utf-8')
}
