import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { inject } from 'tsyringe'
import type { RouteRegistry, RegisteredRoute } from '../../router/route-registry'
import { ROUTER_TOKENS } from '../../router/router.tokens'
import { Command } from '../command'

/**
 * Generate TypeScript types for named routes.
 *
 * Outputs a `stratal.d.ts` file with `StratalRouteMap` augmentation
 * that provides autocomplete and type-safe params for `route()` and `ctx.route()`.
 *
 * @example
 * ```bash
 * quarry route:types                           # → src/stratal.d.ts
 * quarry route:types --output=types/routes.d.ts
 * ```
 */
export class RouteTypesCommand extends Command {
  static command = 'route:types {--output=src/stratal.d.ts : Output file path}'
  static description = 'Generate TypeScript types for named routes'

  constructor(@inject(ROUTER_TOKENS.RouteRegistry) private registry: RouteRegistry) {
    super()
  }

  handle(): number | undefined {
    const outputPath = resolve(this.string('output') || 'src/stratal.d.ts')
    const namedRoutes = this.registry.named()

    if (namedRoutes.length === 0) {
      this.warn('No named routes found. Add name to your @Route() or @Get()/@Post() decorators.')
      return 0
    }

    const content = this.generateDeclaration(namedRoutes)
    writeFileSync(outputPath, content, 'utf-8')
    this.info(`Generated route types for ${namedRoutes.length} named routes → ${outputPath}`)

    return undefined
  }

  /**
   * Generate the StratalRouteMap declaration content.
   */
  private generateDeclaration(routes: RegisteredRoute[]): string {
    const entries = routes
      .filter((r): r is RegisteredRoute & { name: string } => r.name !== undefined)
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(route => {
        const allParams = [...route.paramNames, ...route.domainParamNames]
        const paramsType = allParams.length === 0
          ? 'never'
          : `{ ${allParams.map(p => `${p}: string`).join('; ')} }`
        return `    '${route.name}': { params: ${paramsType} }`
      })
      .join('\n')

    return [
      '// Auto-generated by `quarry route:types` — do not edit manually',
      "declare module 'stratal/router' {",
      '  interface StratalRouteMap {',
      entries,
      '  }',
      '}',
      '',
      'export {}',
      '',
    ].join('\n')
  }
}
