import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { inject } from 'tsyringe'
import type { RouteRegistry, RegisteredRoute } from '../../router/route-registry'
import { ROUTER_TOKENS } from '../../router/router.tokens'
import type { LocalePathService } from '../../router/services/locale-path.service'
import { Command } from '../command'

/**
 * Generate TypeScript types for named routes.
 *
 * Outputs a `stratal.d.ts` file with `StratalRouteMap` augmentation
 * that provides autocomplete and type-safe params for `route()` and `ctx.route()`.
 *
 * @example
 * ```bash
 * quarry route:types                           # → src/stratal.d.ts
 * quarry route:types --output=types/routes.d.ts
 * ```
 */
export class RouteTypesCommand extends Command {
  static command = 'route:types {--output=src/stratal.d.ts : Output file path}'
  static description = 'Generate TypeScript types for named routes'

  constructor(
    @inject(ROUTER_TOKENS.RouteRegistry) private registry: RouteRegistry,
    @inject(ROUTER_TOKENS.LocalePathService) private localePathService: LocalePathService,
  ) {
    super()
  }

  handle(): number | undefined {
    const outputPath = resolve(this.string('output') || 'src/stratal.d.ts')
    const namedRoutes = this.registry.named()

    if (namedRoutes.length === 0) {
      this.warn('No named routes found. Add name to your @Route() or @Get()/@Post() decorators.')
      return 0
    }

    const content = this.generateDeclaration(namedRoutes)
    writeFileSync(outputPath, content, 'utf-8')
    this.info(`Generated route types for ${namedRoutes.length} named routes → ${outputPath}`)

    return undefined
  }

  /**
   * Generate the StratalRouteMap declaration content.
   */
  private generateDeclaration(routes: RegisteredRoute[]): string {
    const localeConfig = this.localePathService.enabled ? this.localePathService.localePathConfig : null
    const localeType = localeConfig
      ? localeConfig.allLocales.map(l => `'${l}'`).join(' | ')
      : null
    const localeOptional = localeConfig ? this.localePathService.prefixDefaultLocale !== true : false

    const entries = routes
      .filter((r): r is RegisteredRoute & { name: string } => r.name !== undefined)
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(route => {
        const paramEntries = [
          ...route.paramNames.map(p => `${p}: string`),
          ...route.domainParamNames.map(p => `${p}: string`),
        ]

        if (localeType && route.localePaths?.length) {
          const optionalMarker = localeOptional ? '?' : ''
          paramEntries.push(`locale${optionalMarker}: StratalLocale`)
        }

        // Extra keys become query-string params at runtime, so allow any
        // string key. Typed path/domain params above still take precedence.
        const indexSignature = localeType && route.localePaths?.length
          ? '[key: string]: string | StratalLocale | undefined'
          : '[key: string]: string | undefined'
        paramEntries.push(indexSignature)

        const paramsType = `{ ${paramEntries.join('; ')} }`
        return `    '${route.name}': { params: ${paramsType} }`
      })
      .join('\n')

    const lines = [
      '// Auto-generated by `quarry route:types` — do not edit manually',
      "declare module 'stratal/router' {",
    ]

    if (localeType) {
      lines.push(`  type StratalLocale = ${localeType}`)
      lines.push('')
    }

    lines.push(
      '  interface StratalRouteMap {',
      entries,
      '  }',
      '}',
    )

    return [
      ...lines,
      '',
      'export {}',
      '',
    ].join('\n')
  }
}
