import type { SchemaDef } from '@zenstackhq/schema'

/**
 * Augment with schema, default connection, and per-connection slicing
 * (auto-generated by @stratal/zenstack-plugin).
 *
 * @example
 * ```typescript
 * declare module '@stratal/framework/database' {
 *   interface StratalDatabase {
 *     schema: SchemaType
 *     defaultConnection: 'main'
 *     slicing: {
 *       main: { includedModels: readonly ['User', 'Post'] }
 *       analytics: { includedModels: readonly ['AnalyticsEvent'] }
 *     }
 *   }
 * }
 * ```
 */
export interface StratalDatabase {}

/** Infer the shared schema type from augmentation, falling back to SchemaDef */
export type InferDatabaseSchema =
  StratalDatabase extends { schema: infer S extends SchemaDef } ? S : SchemaDef

/** Connection name with autocomplete when augmented, string fallback otherwise */
export type ConnectionName =
  StratalDatabase extends { slicing: infer R }
    ? keyof R extends never ? string : Extract<keyof R, string>
    : string

/** Default connection name from augmentation */
export type DefaultConnectionName =
  StratalDatabase extends { defaultConnection: infer N extends string } ? N : string

/** Resolve slicing options for a named connection */
export type InferConnectionSlicing<K extends string> =
  StratalDatabase extends { slicing: infer R }
    ? K extends keyof R ? R[K] : never
    : never

/**
 * Internal context used by database service for dynamic event emission
 * @internal
 */
export interface InternalDatabaseEventContext {
  data: unknown
  result?: unknown
}
