import type { SchemaDef } from '@zenstackhq/schema'

/**
 * Augment with shared schema (auto-generated by @stratal/zenstack-plugin).
 *
 * @example
 * ```typescript
 * declare module '@stratal/framework/database' {
 *   interface DatabaseSchema { type: SchemaType }
 * }
 * ```
 */
export interface DatabaseSchema {}

/**
 * Augment with per-connection slicing (auto-generated by @stratal/zenstack-plugin).
 *
 * @example
 * ```typescript
 * declare module '@stratal/framework/database' {
 *   interface DatabaseSlicingRegistry {
 *     main: { includedModels: readonly ['User', 'Post'] }
 *     analytics: { includedModels: readonly ['AnalyticsEvent'] }
 *   }
 * }
 * ```
 */
export interface DatabaseSlicingRegistry {}

/**
 * Augment with default connection name (auto-generated by @stratal/zenstack-plugin).
 *
 * @example
 * ```typescript
 * declare module '@stratal/framework/database' {
 *   interface DefaultDatabaseConnection { name: 'main' }
 * }
 * ```
 */
export interface DefaultDatabaseConnection {}

/** Infer the shared schema type from augmentation, falling back to SchemaDef */
export type InferDatabaseSchema = DatabaseSchema extends { type: infer S extends SchemaDef } ? S : SchemaDef

/** Connection name with autocomplete when augmented, string fallback otherwise */
export type ConnectionName = keyof DatabaseSlicingRegistry extends never
  ? string
  : Extract<keyof DatabaseSlicingRegistry, string>

/** Default connection name from augmentation */
export type DefaultConnectionName =
  DefaultDatabaseConnection extends { name: infer N extends string } ? N : string

/** Resolve slicing options for a named connection */
export type InferConnectionSlicing<K extends string> =
  K extends keyof DatabaseSlicingRegistry ? DatabaseSlicingRegistry[K] : never

/**
 * Internal context used by database service for dynamic event emission
 * @internal
 */
export interface InternalDatabaseEventContext {
  data: unknown
  result?: unknown
}
