// Auto-generated by @stratal/inertia. Do not edit.
declare global {
  type DashboardPageProps = { stats: { total: number; recent: number; }; activeUsers: number }
  type HomePageProps = { message: string; noteCount: number }
  type NotesCreatePageProps = Record<string, never>
  type NotesEditPageProps = { note: { id: string; title: string; content: string; createdAt: string; updatedAt: string } }
  type NotesIndexPageProps = { notes: Array<{ id: string; title: string; content: string; createdAt: string; updatedAt: string }>; stats: { total: number; recent: number; }; categories: ["general", "work", "personal"]; timestamp: number; page: number }
  type NotesShowPageProps = { note: { id: string; title: string; content: string; createdAt: string; updatedAt: string }; comments: Array<{ id: string; author: string; body: string }>; metadata: { viewCount: number; lastViewed: string; } }
}

declare module '@stratal/inertia' {
  interface InertiaPageRegistry {
    'Dashboard': DashboardPageProps
    'Home': HomePageProps
    'notes/Create': NotesCreatePageProps
    'notes/Edit': NotesEditPageProps
    'notes/Index': NotesIndexPageProps
    'notes/Show': NotesShowPageProps
  }
}

declare module '@inertiajs/core' {
  interface InertiaConfig {
    flashDataType: { success?: string; error?: string }
    sharedPageProps: {
      appName: "Stratal Notes"
      locale: string
      translations: Record<string, string>
      currentNote?: string
    }
  }
}

export {}
