// Auto-generated by @stratal/inertia. Do not edit.
declare module '@stratal/inertia' {
  interface InertiaPageRegistry {
    'Dashboard': { stats: { total: number; recent: number; }; activeUsers: number }
    'Home': { message: string; noteCount: unknown }
    'notes/Create': Record<string, never>
    'notes/Edit': { note: { id: string; title: string; content: string; createdAt: string; updatedAt: string } }
    'notes/Index': { notes: unknown; stats: unknown; categories: unknown; timestamp: unknown; page: number }
    'notes/Show': { note: { id: string; title: string; content: string; createdAt: string; updatedAt: string }; comments: unknown; metadata: unknown }
  }
}

declare module '@inertiajs/core' {
  interface InertiaConfig {
    flashDataType: { success?: string; error?: string }
    sharedPageProps: {
      appName: "Stratal Notes"
      locale: string
      translations: Record<string, string>
      currentNote?: string
    }
  }
}

export {}
