// Auto-generated by @stratal/inertia. Do not edit.
declare module '@stratal/inertia' {
  interface InertiaPageRegistry {
    'Home': { message: string; noteCount?: number | undefined; }
    'notes/Create': Record<string, never>
    'notes/Edit': { note: Note; }
    'notes/Index': { notes: Note[]; stats?: Stats | undefined; page: number; }
    'notes/Show': { note: Note; comments?: Comment[] | undefined; }
  }
}

declare module '@inertiajs/core' {
  interface InertiaConfig {
    sharedPageProps: { appName: "Stratal Notes"; flash: string | null }
  }
}

export {}
