name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: |
          yarn workspace stratal build
          yarn workspace @stratal/framework build
          yarn workspace @stratal/testing build
          yarn workspace @stratal/seeders build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: yarn changeset version && yarn install
          publish: yarn release
          createGithubReleases: true
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
